package ru.chaplyginma.task;

import java.util.Set;

/**
 * Represents the result of a mapping task, containing a set of output files.
 *
 * <p>The {@code MapTaskResult} record encapsulates the results generated by a map task,
 * specifically the output files created as a result of processing input data.</p>
 */
public record MapTaskResult(
        Set<String> files
) {
}
